### PR TITLE
Fix gradient issue with PFFT3D

### PR DESCRIPTION
**Pull request by ASKabalan**

### CODE REVIEW

**Comment by ASKabalan** [comment]
Closes https://github.com/DifferentiableUniverseInitiative/jaxDecomp/issues/48

**Comment by EiffL** [comment]
Oh wait.... does this mean that even the non-distributed jax implementation has faulty gradients????

**Comment by EiffL** [comment]
if so, this needs to be merged ASAP. We can't have a published version of jaxpm with unreliable gradients....

**Comment by ASKabalan** [comment]
I was going to publish this in v0.2.3 
Do want this right now?

The error is very simple 
The promotion to complex needs to be outside the custom vjp

**Comment by EiffL** [comment]
This is what happens when I try to get jaxpm gradients now:

image

Of course I want it to be merge as soon as possible, this is breaking the core functionality of jaxpm.

**Review by EiffL — APPROVED** [review]
I tested it, and it works :-)

**Pull request merged**
